version: '3.8'

services:
  laravel:
    build: ./arvegatuPramuka
    container_name: laravel_app
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./arvegatuPramuka:/var/www
    depends_on:
      - db
    networks:
      - app_network

  flask:
    build: ./project_cluster/flask_api
    container_name: flask_app
    ports:
      - "5000:5000"
    environment:
      FLASK_APP: app.py   # sesuaikan dengan file utama Flask kamu
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: app_db
      DB_USERNAME: root
      DB_PASSWORD: root
    volumes:
      - ./project_cluster/flask_api:/app
    depends_on:
      - db
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    container_name: nginx_laravel
    ports:
      - "8000:80"
    volumes:
      - ./arvegatuPramuka:/var/www
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - laravel
    networks:
      - app_network

  db:
    image: mysql:8
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: app_db
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  db_data:
